apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:  
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/two-tier-flask-app/mysql-data 
    #this is the path on the node where mysql data will be stored. You can change it as per your requirement. Make sure that this path exists on the node and has proper permissions.
    
