apiVersion: apps/v1
kind: Deployment
metadata:
  name:  flask-app
  namespace: default
  labels:
    app:  flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  flask-app
    spec:
      containers:
      - name:  flask-app-container
        image:  ashutoshkumarmahanta/flask-app:latest
        env:
          - name: MYSQL_HOST
            value: "mysql"  #this is mysql service cluster IP address
          - name: MYSQL_USER
            value: "admin"
          - name: MYSQL_PASSWORD
            value: "admin"
          - name: MYSQL_DB
            value: "myDb"
        ports:
        - containerPort: 5000
      imagePullPolicy: Always
